name: On Manual 1 Public Runner

on:
  workflow_dispatch:

jobs:
    my_job:
      runs-on: self-hosted
      container: 
        image: summerwind/actions-runner:latest
      steps:
      - run: |
          sleep 1h
