name: On Manual 1 Public Runner

on:
  pull_request:
  push:

jobs:
    my_job:
      runs-on: ubuntu-latest
      steps:
      - run: |
          echo "GITHUB_REF : $GITHUB_REF"
          echo "GITHUB_HEAD_REF : $GITHUB_HEAD_REF"
          echo "GITHUB_BASE_REF : $GITHUB_BASE_REF"
          echo "GITHUB_EVENT_NAME : $GITHUB_EVENT_NAME"
