name: On Manual 1 Public Runner

on:
  workflow_dispatch:

jobs:
    my_job:
      concurrency: group-feature
      runs-on: ubuntu-latest
      container: 
        image: summerwind/actions-runner:latest
      steps:
      - run: |
          #pip install meson
          echo hello
      - run: |
          set +e
          echo $HOME
          ls -al ~
          which meson
          ls -al ~/.local/bin  
          ls -al $HOME
